config/routes.rb
Rails.application.routes.draw do

  root 'urls#new'

  resources :urls, only: [:index, :new, :create]

  get ':id', to: 'urls#show', as: 'url'

end

app/models/url.rb
class Url < ActiveRecord::Base
  validates_presence_of :original

  def self.unique_rand_id letters
    loop do
      @rd_id=(1..8).map {letters[rand letters.length]}.join
      break if self.where('random_id = ?', @rd_id).empty?
    end
    @rd_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def index
    @urls=Url.all
  end

  def show
    @url=Url.find_by_random_id params[:id]

    if @url
      redirect_to @url.original
    else
      flash[:alert]='Shortened url not registered..'
      redirect_to urls_path
    end
  end

  def new
    @url=Url.new
  end

  def create
    @url=Url.new url_params

    letters||=[('a'..'z'), ('A'..'Z'), (0..9)].map {|i| i.to_a}.flatten
    @url.random_id=Url.unique_rand_id letters

    if @url.save
      flash[:notice]='Short Url Created..'

      redirect_to urls_path
    else
      flash[:alert]='Short Url could not be created..'
      render :new
    end
  end


  private
    def url_params
      params.require(:url).permit :original
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% elsif flash[:alert] %>
    <%= flash[:alert] %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/urls/index.erb
<h1>urlShortener</h1>

<% @urls.each do |url| %>
  <p>
    <%= link_to url.random_id, url_path(id: url.random_id) %> : <%= url.original %>
  </p>
<% end %>

<%= link_to 'urlShortener New', new_url_path %>

app/views/urls/new.erb
<h1>urlShortener New</h1>

<% if @url.errors.any? %>
  <% @url.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

<%= form_for @url do |f| %>
  <%= f.label :url %> : <%= f.text_field :original %>
  <%= f.submit 'urlShorten' %>
<% end %>